version: 2

.test: &test
    working_directory: ~/repo
    steps:
        - checkout
        - restore_cache:
              keys:
                  - composer-{{ .Environment.PHP_VERSION }}-{{ checksum "composer.json" }}
        - run: apt-get -yqq update
        - run: apt-get -yqq install git unzip zip libpq-dev mysql-client libpng-dev
        - run: docker-php-ext-install pdo_pgsql pdo_mysql gd
        - run: curl -sS https://getcomposer.org/installer | php
        - run: chmod +x composer.phar
        - run: mv composer.phar /usr/local/bin/composer
        - run: composer config -g github-oauth.github.com $GITHUB_TOKEN
        - run: composer install -n --prefer-dist --no-progress -o
        - save_cache:
              key: composer-{{ .Environment.PHP_VERSION }}-{{ checksum "composer.json" }}
              paths:
                  - vendor/
        - run: ./vendor/bin/phpunit
        - persist_to_workspace:
              root: ./
              paths:
                  - vendor

jobs:
    "php-7.2":
        <<: *test
        docker:
            - image: php:7.2
        environment:
            PHP_VERSION: 7.2

    "php-7.3":
        <<: *test
        docker:
            - image: php:7.3
        environment:
            PHP_VERSION: 7.3

    phpcs:
        docker:
            - image: php:7.2
        working_directory: ~/repo
        steps:
            - checkout
            - attach_workspace:
                  at: ./
            - run: ./vendor/bin/phpcs

    coverage:
        docker:
            - image: php:7.2
        working_directory: ~/repo
        steps:
            - checkout
            - attach_workspace:
                  at: ./
            - run: pecl install xdebug
            - run: docker-php-ext-enable xdebug
            - run: ./vendor/bin/phpunit --coverage-clover=coverage.xml
            - run: bash <(curl -s https://codecov.io/bash)

    subsplit:
        docker:
            - image: php:7.2
        working_directory: ~/repo
        steps:
            - checkout
            - run: apt-get -yqq update
            - run: apt-get -yqq install git
            - run: mkdir ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
            - run: git clone git@github.com:dflydev/git-subsplit.git ~/subsplit
            - run: cp ~/subsplit/git-subsplit.sh "$(git --exec-path)"/git-subsplit
            - run: bash build/tenancy-split.sh

workflows:
    version: 2
    test:
        jobs:
            - "php-7.2"
            - "php-7.3"
            - phpcs:
                  requires:
                      - "php-7.2"
                      - "php-7.3"
            - coverage:
                  requires:
                      - "php-7.2"
                      - "php-7.3"
            - subsplit:
                  requires:
                      - phpcs
                      - coverage
                  filters:
                      branches:
                          only:
                              - master
